version: '3.8'

services:
  twap-service:
    build: .
    environment:
      FOSSIL_DB_CONNECTION_STRING: ${FOSSIL_DB_CONNECTION_STRING}
      PITCHLAKE_DB_CONNECTION_STRING: ${PITCHLAKE_DB_CONNECTION_STRING}
      INITIAL_BLOCK_NUMBER: ${INITIAL_BLOCK_NUMBER}
      USE_DEMO_DATA: ${USE_DEMO_DATA:-false}
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "node", "-e", "console.log('Health check')"]
      interval: 30s
      timeout: 10s
      retries: 3